### PR TITLE
fix: ensure ftruncate writes envelope

### PR DESCRIPTION
**Pull request by steven-halaka**
Here's an attempt at a fix but I very strongly would love a thorough review and maybe some suggestions for other tests to run.

Extracted the creation of the envelope and wrapper header xattrs into a `File` method (`initializeEnvelopeKey`) and call it from both `doWrite` and `truncateGrowFile`.

### CODE REVIEW

**Comment by hokie228** [comment]
That makes sense and actually could explain some of the other issues people have seen with certain products.  I'd love @landrew3 opinion as well as he worked on the envelope encryption.  I would be curious if the non-envelope option has the same issue or not.  We might want to run it in "standard" mode as well to see if truncate causes any issues there.  When running this in envelope mode, can you just truncate a file and cause these issues?

**Comment by steven-halaka** [comment]
> That makes sense and actually could explain some of the other issues people have seen with certain products. I'd love @landrew3 opinion as well as he worked on the envelope encryption. I would be curious if the non-envelope option has the same issue or not. We might want to run it in "standard" mode as well to see if truncate causes any issues there. When running this in envelope mode, can you just truncate a file and cause these issues?

I did build master, initialized a new mount, and ran the test successfully without any of these changes.

Yes, the following test causes a panic on tkfs branch:
```
package main
import "os"
func main() {
        fn := "lizard/local/data/index/foo"
        os.Remove(fn)
        f, _ := os.OpenFile(fn, os.O_CREATE|os.O_WRONLY, 0600)
        f.Truncate(16384)
        f.Write(make([]byte, 16384))
}
```

A breakdown of what I found while debugging is at https://trustedkeep.atlassian.net/browse/TK-237?focusedCommentId=11339

**Comment by landrew3** [comment]
I think @steven-halaka s got it. There's no obvious other places where the header would even be created, so this seems like the one. It also makes sense that this doesn't happen out side of envelope mode since the xattrs are only used/set up there.

**Comment by steven-halaka** [comment]
I couldn't quite get [xfstests](https://github.com/kdave/xfstests) to run (might be worth a backlog ticket) but this seems to be working through all sorts of truncating (grow/shrink) and as an rclone vfs cache dir.

**Comment by hokie228** [comment]
The standard xfstests don't work with FUSE filesystems.  We had an adapted one (from https://github.com/rfjakob/fuse-xfstests I think) that we ran long ago.  Not sure if we still have the setup available or not.  In either case, this looks good for now.

**Pull request merged**
